### ISSUE TITLE
The Setup Instruction link in the readme is broken

### ISSUE THREAD

**Issue by Kezzsim** [silent-disco/node-disco#15]
I'm having a hard way finding out how this project was implemented, I've been looking for a good web player with metadata for an Icecast stream from Traktor during a Silent Disco but I haven't seen any yet.

The broken link is: https://github.com/silent-disco/node-disco/blob/master/docs/DEV_SETUP.md

thanks

**Comment by nikku** [comment]
This project is not what you're looking for. It is a collaborative silent-disco based on Soundcloud tracks where people connect to via a IRC style chat.

**Comment by nikku** [comment]
Updated link to DEV_SETUP via https://github.com/silent-disco/node-disco/commit/556fde1191694458c9298134a392b80e147ee097.
